"use client";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Footer } from "@/components/footer";
import Header from "@/components/header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { UserProvider } from "@/components/context/user_context";
import { ProfileProvider } from "@/components/context/profile_context";
import { ProductProvider } from "@/components/context/product_context";
import { CategoryProvider } from "@/components/context/category_context";
import { CartProvider } from "@/components/context/cart_context";
import { WishListProvider } from "@/components/context/wishlist_context";
import { Suspense } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Suspense>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <UserProvider>
                <ProfileProvider>
                  <CategoryProvider>
                    <ProductProvider>
                      <CartProvider>
                        <WishListProvider>
                          <Header />
                          {children}
                          <Footer />
                        </WishListProvider>
                      </CartProvider>
                    </ProductProvider>
                  </CategoryProvider>
                </ProfileProvider>
              </UserProvider>
              <ToastContainer />
            </ThemeProvider>
          </Suspense>
        </body>
      </html>
    </>
  );
}
